### ISSUE TITLE
[Unable to add sources for RSS feeds and Reddit]

### ISSUE THREAD

**Issue by theorbow** [feeddeck/feeddeck#169]
I've recently stumbled upon this fantastic application. However, I've encountered a limitation where I can't add any more Reddit feeds beyond the initial 10 I've added. Additionally, I'm unable to add any RSS feeds in Feeddeck. The error I'm getting is: Failed to add source: Instance of 'Function Exception' 

Platform: Manjaro Linux (Flatpak)

I've attached some screenshots below for your reference: 
![Screenshot_2024-06-01_23-51-01](https://github.com/feeddeck/feeddeck/assets/148376362/0ab4dae1-c934-4542-b954-67d422b7db79)
![Screenshot_2024-06-02_22-24-01](https://github.com/feeddeck/feeddeck/assets/148376362/83fd9c37-23e9-47c1-a557-6901b4dfc197)
![Screenshot_2024-06-02_22-35-04](https://github.com/feeddeck/feeddeck/assets/148376362/ab193d15-abef-444d-8356-07d665a100b9)
![Screenshot_2024-06-02_22-47-18](https://github.com/feeddeck/feeddeck/assets/148376362/933e6267-5013-42ab-be23-972d088507ab)

**Comment by ricoberger** [comment]
Hi @theorbow, once you added 10 sources (the type doesn't matter) you need a premium account (https://feeddeck.app/pricing). As an alternative you can self host Supabase or use the free offering (see https://supabase.com). The instructions for the setup can be found in the contributing guidelines https://github.com/feeddeck/feeddeck/blob/main/CONTRIBUTING.md#hosting.

**Comment by theorbow** [comment]
Thank you for the response.
