### ISSUE TITLE
On computer can't move to new feed added on the source

### ISSUE THREAD

**Issue by David7ce** [feeddeck/feeddeck#25]
## Describe the Bug

When adding rss feed to one source after more than 4 feeds, I can't move to the five or so feed. Basically on PC you can't move the bar where are located the RSS Feed on circles.

## Platform

- [ ] Android
- [ ] iOS
- [x] Linux
- [ ] macOS
- [ ] Windows
- [x] Web

## To Reproduce

1. Go to one source
2. Add multiple RSS Feed more than five
3. Try to go to the last feed
4. Can't move the feeds.

## Expected behavior

I want to move from one feed to another and move the bar of feeds. I think it was thinked for mobile screens but nor for computers.

## Screenshot

![Screenshot_20231012_133032](https://github.com/feeddeck/feeddeck/assets/79609649/978e440b-4ea9-419a-8009-218d6bf8737b)

**Comment by ricoberger** [comment]
Hi @David7ce, thanks for reporting the issue. I can confirm that this is an issue on Linux, Windows and the Web version when there are no touch gestures or trackpad.

To fix this issue, I changed the scrolling behavior of the app to also support drag gestures from the mouse for scrolling in #27.

A new version with the fix should be released over the weekend. If you still have issues afterwards or if you encounter any other issues please let me know.

**Comment by David7ce** [comment]
Sorry but for me, horizontal scroll in the sources menu is not possible. I only can see the maximum width of 4 and a half circle sources and cant move to the next one.

**Comment by ricoberger** [comment]
The new version with the fix should now be available.
